import{a as w,S as L,i as l}from"./assets/vendor-C4-ZuMk8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const S="47000249-41843abe91023242d8e7e2eb0",$="https://pixabay.com/api/";async function f(r,t,a=15){const n=`${$}?key=${S}&q=${r}&image_type=photo&orientation=horizontal&safesearch=true&page=${t}&per_page=${a}`;try{return(await w.get(n)).data}catch(e){throw console.error("Error fetching images:",e),e}}let g;function h(r){const t=document.querySelector(".gallery"),a=r.map(({webformatURL:n,largeImageURL:e,tags:o,likes:s,views:m,comments:y,downloads:b})=>`<a class='gallery_item' href="${e}">
        <img src="${n}" alt="${o}" width='360px' height='200px' loading="lazy" />
        <div class='info'>
        <p><b>Likes:</b>${s}</p>
        <p><b>Views:</b>${m}</p>
        <p><b>Comments:</b>${y}</p>
        <p><b>DownLoads:</b>${b}</p>
        </div>
      </a>
      `).join("");t.insertAdjacentHTML("beforeend",a),g?g.refresh():g=new L(".gallery a")}function P(){document.querySelector(".gallery").innerHTML=""}const q=document.querySelector("#search-form"),u=document.querySelector("#load-more");let c="",i=1;const d=15;let p=0;q.addEventListener("submit",v);u.addEventListener("click",x);async function v(r){if(r.preventDefault(),c=r.currentTarget.searchQuery.value.trim(),!!c){i=1,P(),u.hidden=!0;try{const t=await f(c,i,d);if(p=t.totalHits,t.hits.length===0){l.warning({title:"Warning",message:"Please enter a search query."});return}h(t.hits),t.totalHits>d&&(u.hidden=!1)}catch(t){console.error(t),l.warning({title:"Warning",message:"Something went wrong. Please try again later."})}}}async function x(){i+=1;try{const r=await f(c,i,d);h(r.hits);const t=Math.ceil(p/d);i>=t&&(u.hidden=!0,l.warning({title:"Success",message:"We're sorry, but you've, reached the end of search results.",position:"topRight",titleColor:"#808080",messageColor:"#000000"})),E()}catch(r){console.error(r),l.warning({message:"Something went wrong. Please try again later."})}}function E(){const{height:r}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
