import{a as b,S as v,i as a}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const S="47000249-41843abe91023242d8e7e2eb0",E="https://pixabay.com/api/",q=15;async function h(t,o){const i={key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:q,page:o};try{return(await b.get(E,{params:i})).data}catch(n){throw console.error("Error fetching images:",n),new Error("Failed to fetch images")}}const f=document.querySelector(".gallery");let P=new v(".gallery a");function g(t){const o=t.map(({webformatURL:i,largeImageURL:n,tags:e,likes:r,views:s,comments:L,downloads:w})=>`
        <div class="gallery-list">
        <a class="gallery-item" href="${n}">
        <img src="${i}" alt="${e}" width='360px' height='200px' loading="lazy" />
        </a>
        <div class="info">
          <p>Likes:<br /> ${r}</p>
          <p>Views:<br /> ${s}</p>
          <p>Comments:<br /> ${L}</p>
          <p>Downloads:<br /> ${w}</p>
          </div>
        </div>
        `).join("");f.insertAdjacentHTML("beforeend",o),P.refresh()}function M(){f.innerHTML=""}const R=document.querySelector(".search-form"),$=document.querySelector(".search-input"),l=document.querySelector(".load-more-btn"),m=document.querySelector("#loader");let d="",c=1;R.addEventListener("submit",B);l.addEventListener("click",O);function x(){m.classList.remove("hidden")}function u(){m.classList.add("hidden")}function A(){l.classList.remove("hidden")}function p(){l.classList.add("hidden")}async function B(t){if(t.preventDefault(),d=$.value.trim(),d===""){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}M(),p(),c=1,await y()}async function O(){c+=1,await y()}async function y(){try{x();const t=await h(d,c);if(t.hits.length===0){a.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}g(t.hits),c>=Math.ceil(t.totalHits/15)?(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),p()):A()}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{u()}}function I(){const t=document.querySelector(".gallery-list"),{height:o}=t.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}l.addEventListener("click",async()=>{try{await h(),g(images),I()}catch(t){console.error(t)}});
//# sourceMappingURL=index.js.map
